### ISSUE TITLE
Test failures: NoMethodError: undefined method `echo?' and `raw' for an instance of File

### ISSUE THREAD

**Issue by junaruga** [ruby/io-console#57]
I got the following 2 failures with the latest master branch Ruby ruby/ruby@ced84beb25 right now. Do you know what's the reason?

```
Failure: test_bad_keyword(TestIO_Console):
  Exception(ArgumentError) with message matches to /unknown keyword:.*bad/.
  [ArgumentError] exception expected, not #<NoMethodError: undefined method `raw' for an instance of File>.
```

```
Failure: test_failed_path(TestIO_Console): [Errno::ENODEV, Errno::ENOTTY, Errno::EBADF, Errno::ENXIO] exception expected, not #<NoMethodError: undefined method `echo?' for an instance of File>.
```

## Reproducing steps

```
$ cat /etc/fedora-release
Fedora release 38 (Thirty Eight)
```

```
$ ruby -v
ruby 3.3.0dev (2023-11-07T10:22:30Z master ced84beb25) [x86_64-linux]

$ which ruby
~/.local/ruby-3.3.0dev-debug-ced84beb25/bin/ruby

$ bundle -v
Bundler version 2.5.0.dev

$ which bundle
~/.local/ruby-3.3.0dev-debug-ced84beb25/bin/bundle
```

```
$ bundle install

$ bundle list
Gems included by the bundle:
  * io-console (0.6.1.dev)
  * power_assert (2.0.3)
  * rake (13.1.0)
  * rake-compiler (1.2.5)
  * test-unit (3.6.1)
  * test-unit-ruby-core (1.0.5)
Use `bundle info` to print more detailed information about a gem
```

```
$ bundle exec rake compile
mkdir -p lib/3.3.0/x86_64-linux/io
mkdir -p tmp/x86_64-linux/io/console/3.3.0/io
cd tmp/x86_64-linux/io/console/3.3.0
/home/jaruga/.local/ruby-3.3.0dev-debug-ced84beb25/bin/ruby -I. ../../../../../ext/io/console/extconf.rb
checking for rb_io_path()... yes
checking for rb_io_descriptor()... yes
checking for rb_io_get_write_io()... yes
checking for rb_io_closed_p()... yes
checking for rb_io_open_descriptor()... yes
checking for termios.h... yes
checking for cfmakeraw() in termios.h... yes
checking for sys/ioctl.h... yes
checking for HAVE_RUBY_FIBER_SCHEDULER_H... yes
creating Makefile
cd -
cd tmp/x86_64-linux/io/console/3.3.0
/bin/gmake
gcc -I. -I/home/jaruga/.local/ruby-3.3.0dev-debug-ced84beb25/include/ruby-3.3.0+0/x86_64-linux -I/home/jaruga/.local/ruby-3.3.0dev-debug-ced84beb25/include/ruby-3.3.0+0/ruby/backward -I/home/jaruga/.local/ruby-3.3.0dev-debug-ced84beb25/include/ruby-3.3.0+0 -I../../../../../ext/io/console -DHAVE_RB_IO_PATH -DHAVE_RB_IO_DESCRIPTOR -DHAVE_RB_IO_GET_WRITE_IO -DHAVE_RB_IO_CLOSED_P -DHAVE_RB_IO_OPEN_DESCRIPTOR -DHAVE_TERMIOS_H -DHAVE_CFMAKERAW -DHAVE_SYS_IOCTL_H -DHAVE_RB_IO_WAIT=1    -fPIC -O0 -fno-fast-math -g3 -ggdb3 -gdwarf-4 -Wall -Wextra -Wdeprecated-declarations -Wdiv-by-zero -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wpointer-arith -Wwrite-strings -Wold-style-definition -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable -Wmisleading-indentation -Wundef  -fPIC  -o console.o -c ../../../../../ext/io/console/console.c
rm -f console.so
gcc -shared -o console.so console.o -L. -L/home/jaruga/.local/ruby-3.3.0dev-debug-ced84beb25/lib -Wl,-rpath,/home/jaruga/.local/ruby-3.3.0dev-debug-ced84beb25/lib -L. -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,--no-as-needed -Wl,--compress-debug-sections=zlib    -Wl,-rpath,/home/jaruga/.local/ruby-3.3.0dev-debug-ced84beb25/lib -L/home/jaruga/.local/ruby-3.3.0dev-debug-ced84beb25/lib -lruby  -lm -lpthread  -lc
cp console.so io/console.so
cd -
mkdir -p tmp/x86_64-linux/stage/lib/3.3.0/x86_64-linux/io
/bin/gmake install sitearchdir=../../../../../lib/3.3.0/x86_64-linux/io sitelibdir=../../../../../lib/3.3.0/x86_64-linux/io target_prefix=
/bin/mkdir -p . ../../../../../lib/3.3.0/x86_64-linux/io
exit > .sitearchdir.-.io.time
/bin/install -c -m 0755 console.so ../../../../../lib/3.3.0/x86_64-linux/io
cp tmp/x86_64-linux/io/console/3.3.0/io/console.so tmp/x86_64-linux/stage/lib/3.3.0/x86_64-linux/io/console.so
```

```
$ bundle exec rake test
/bin/gmake install sitearchdir=../../../../../lib/3.3.0/x86_64-linux/io sitelibdir=../../../../../lib/3.3.0/x86_64-linux/io target_prefix=
/bin/install -c -m 0755 console.so ../../../../../lib/3.3.0/x86_64-linux/io
cp tmp/x86_64-linux/io/console/3.3.0/io/console.so tmp/x86_64-linux/stage/lib/3.3.0/x86_64-linux/io/console.so
Loaded suite /home/jaruga/.local/ruby-3.3.0dev-debug-ced84beb25/lib/ruby/gems/3.3.0+0/gems/rake-13.1.0/lib/rake/rake_test_loader
Started
F
===============================================================================
Failure: test_bad_keyword(TestIO_Console):
  Exception(ArgumentError) with message matches to /unknown keyword:.*bad/.
  [ArgumentError] exception expected, not #<NoMethodError: undefined method `raw' for an instance of File>.
/home/jaruga/.local/ruby-3.3.0dev-debug-ced84beb25/lib/ruby/gems/3.3.0+0/gems/test-unit-ruby-core-1.0.5/lib/core_assertions.rb:446:in `block in assert_raise'
/home/jaruga/.local/ruby-3.3.0dev-debug-ced84beb25/lib/ruby/gems/3.3.0+0/gems/test-unit-ruby-core-1.0.5/lib/core_assertions.rb:532:in `assert'
/home/jaruga/.local/ruby-3.3.0dev-debug-ced84beb25/lib/ruby/gems/3.3.0+0/gems/test-unit-ruby-core-1.0.5/lib/core_assertions.rb:445:in `rescue in assert_raise'
/home/jaruga/.local/ruby-3.3.0dev-debug-ced84beb25/lib/ruby/gems/3.3.0+0/gems/test-unit-ruby-core-1.0.5/lib/core_assertions.rb:433:in `assert_raise'
/home/jaruga/.local/ruby-3.3.0dev-debug-ced84beb25/lib/ruby/gems/3.3.0+0/gems/test-unit-ruby-core-1.0.5/lib/core_assertions.rb:492:in `block in assert_raise_with_message'
/home/jaruga/.local/ruby-3.3.0dev-debug-ced84beb25/lib/ruby/gems/3.3.0+0/gems/test-unit-ruby-core-1.0.5/lib/envutil.rb:258:in `with_default_internal'
/home/jaruga/.local/ruby-3.3.0dev-debug-ced84beb25/lib/ruby/gems/3.3.0+0/gems/test-unit-ruby-core-1.0.5/lib/core_assertions.rb:491:in `assert_raise_with_message'
/home/jaruga/var/git/ruby/io-console/test/io/console/test_io_console.rb:55:in `test_bad_keyword'
     52:
     53:   def test_bad_keyword
     54:     omit if RUBY_ENGINE == 'jruby'
  => 55:     assert_raise_with_message(ArgumentError, /unknown keyword:.*bad/) do
     56:       File.open(IO::NULL) do |f|
     57:         f.raw(bad: 0)
     58:       end
===============================================================================
F
===============================================================================
Failure: test_failed_path(TestIO_Console): [Errno::ENODEV, Errno::ENOTTY, Errno::EBADF, Errno::ENXIO] exception expected, not #<NoMethodError: undefined method `echo?' for an instance of File>.
/home/jaruga/.local/ruby-3.3.0dev-debug-ced84beb25/lib/ruby/gems/3.3.0+0/gems/test-unit-ruby-core-1.0.5/lib/core_assertions.rb:446:in `block in assert_raise'
/home/jaruga/.local/ruby-3.3.0dev-debug-ced84beb25/lib/ruby/gems/3.3.0+0/gems/test-unit-ruby-core-1.0.5/lib/core_assertions.rb:532:in `assert'
/home/jaruga/.local/ruby-3.3.0dev-debug-ced84beb25/lib/ruby/gems/3.3.0+0/gems/test-unit-ruby-core-1.0.5/lib/core_assertions.rb:445:in `rescue in assert_raise'
/home/jaruga/.local/ruby-3.3.0dev-debug-ced84beb25/lib/ruby/gems/3.3.0+0/gems/test-unit-ruby-core-1.0.5/lib/core_assertions.rb:433:in `assert_raise'
/home/jaruga/var/git/ruby/io-console/test/io/console/test_io_console.rb:46:in `block in test_failed_path'
     43:     exceptions.compact!
     44:     omit if exceptions.empty?
     45:     File.open(IO::NULL) do |f|
  => 46:       e = assert_raise(*exceptions) do
     47:         f.echo?
     48:       end
     49:       assert_include(e.message, IO::NULL)
/home/jaruga/var/git/ruby/io-console/test/io/console/test_io_console.rb:45:in `open'
/home/jaruga/var/git/ruby/io-console/test/io/console/test_io_console.rb:45:in `test_failed_path'
===============================================================================
Finished in 1.517363165 seconds.
-------------------------------------------------------------------------------
3 tests, 8 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
33.3333% passed
-------------------------------------------------------------------------------
1.98 tests/s, 5.27 assertions/s
rake aborted!
Command failed with status (1)
/home/jaruga/.local/ruby-3.3.0dev-debug-ced84beb25/bin/bundle:25:in `load'
/home/jaruga/.local/ruby-3.3.0dev-debug-ced84beb25/bin/bundle:25:in `<main>'
Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by junaruga** [comment]
I tried the above reproducing steps on the latest master branch fe24d021b14b054b64dbb561fc340962be09c58e on Ruby 4.1.0dev ruby/ruby@3ef48ef9c8fb3c19d64b4bcf41ed10edb0bfeecc. And the `bundle exec rake test` passed without test failures.

Below is my environment and the command log.

My environment is below.

```
$ cat /etc/fedora-release
Fedora release 43 (Forty Three)

$ uname -m
x86_64

$ gcc --version
gcc (GCC) 15.2.1 20260123 (Red Hat 15.2.1-7)
Copyright (C) 2025 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ ruby -v
ruby 4.1.0dev (2026-05-19T11:31:50Z master 3ef48ef9c8) +PRISM [x86_64-linux]

$ which ruby
~/.local/ruby-4.1.0-debug-3ef48ef9c8-openssl-4.1.0-7194354488/bin/ruby

$ bundle -v
4.1.0.dev

$ which bundle
~/.local/ruby-4.1.0-debug-3ef48ef9c8-openssl-4.1.0-7194354488/bin/bundle
```

The command log is below.

```
$ pwd
/home/jaruga/git/ruby/io-console

$ bundle install
Fetching gem metadata from https://rubygems.org/.........
Local specification for rdoc-7.2.0 has different dependencies than the remote gem, ignoring it
Resolving dependencies...
Fetching erb 6.0.6
Fetching rbs 4.1.2
Fetching test-unit 3.7.8
Fetching rdoc 8.0.0
Fetching rake-compiler 1.3.1
Installing erb 6.0.6 with native extensions
Installing rake-compiler 1.3.1
Installing test-unit 3.7.8
Installing rdoc 8.0.0
Installing rbs 4.1.2 with native extensions
Bundle complete! 7 Gemfile dependencies, 12 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

$ bundle list
Gems included by the bundle:
  * erb (6.0.6)
  * io-console (0.8.2)
  * logger (1.7.0)
  * power_assert (3.0.1)
  * prism (1.9.0)
  * rake (13.4.2)
  * rake-compiler (1.3.1)
  * rbs (4.1.2)
  * rdoc (8.0.0)
  * test-unit (3.7.8)
  * test-unit-ruby-core (1.0.14)
  * tsort (0.2.0)
Use `bundle info` to print more detailed information about a gem

$ bundle exec rake compile
mkdir -p .libs/4.1.0/x86_64-linux/io
mkdir -p tmp/x86_64-linux/io/console/4.1.0/io
cd tmp/x86_64-linux/io/console/4.1.0
/home/jaruga/.local/ruby-4.1.0-debug-3ef48ef9c8-openssl-4.1.0-7194354488/bin/ruby -I. ../../../../../ext/io/console/extconf.rb
checking for rb_interned_str_cstr()... yes
checking for rb_ractor_local_storage_value_newkey()... yes
checking for rb_io_descriptor() in ruby/io.h... yes
checking for rb_io_path() in ruby/io.h... yes
checking for rb_io_closed_p() in ruby/io.h... yes
checking for rb_io_open_descriptor() in ruby/io.h... yes
checking for termios.h... yes
checking for cfmakeraw() in termios.h... yes
checking for sys/ioctl.h... yes
checking for HAVE_RUBY_FIBER_SCHEDULER_H... yes
checking for ttyname_r()... yes
checking for rb_prepend_module()... yes
creating Makefile
cd -
cd tmp/x86_64-linux/io/console/4.1.0
/bin/gmake
gcc -I. -I/home/jaruga/.local/ruby-4.1.0-debug-3ef48ef9c8-openssl-4.1.0-7194354488/include/ruby-4.1.0+1/x86_64-linux -I/home/jaruga/.local/ruby-4.1.0-debug-3ef48ef9c8-openssl-4.1.0-7194354488/include/ruby-4.1.0+1/ruby/backward -I/home/jaruga/.local/ruby-4.1.0-debug-3ef48ef9c8-openssl-4.1.0-7194354488/include/ruby-4.1.0+1 -I../../../../../ext/io/console -DHAVE_RB_INTERNED_STR_CSTR -DHAVE_RB_RACTOR_LOCAL_STORAGE_VALUE_NEWKEY -DHAVE_RB_IO_DESCRIPTOR -DHAVE_RB_IO_PATH -DHAVE_RB_IO_CLOSED_P -DHAVE_RB_IO_OPEN_DESCRIPTOR -DHAVE_TERMIOS_H -DHAVE_CFMAKERAW -DHAVE_SYS_IOCTL_H -DHAVE_RB_IO_WAIT=1 -DHAVE_TTYNAME_R -DHAVE_RB_PREPEND_MODULE    -fPIC   -O0 -fno-fast-math -g3 -ggdb3 -gdwarf-4 -Wall -Wextra -Wdeprecated-declarations -Wdiv-by-zero -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wpointer-arith -Wwrite-strings -Wold-style-definition -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable -Wmisleading-indentation -Wundef  -fPIC  -o console.o -c ../../../../../ext/io/console/console.c
rm -f console.so
gcc -shared -o console.so console.o -L. -L/home/jaruga/.local/ruby-4.1.0-debug-3ef48ef9c8-openssl-4.1.0-7194354488/lib -Wl,-rpath,/home/jaruga/.local/ruby-4.1.0-debug-3ef48ef9c8-openssl-4.1.0-7194354488/lib -L. -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,--no-as-needed -Wl,--compress-debug-sections=zlib    -Wl,-rpath,/home/jaruga/.local/ruby-4.1.0-debug-3ef48ef9c8-openssl-4.1.0-7194354488/lib -L/home/jaruga/.local/ruby-4.1.0-debug-3ef48ef9c8-openssl-4.1.0-7194354488/lib -lruby  -lm -lpthread  -lc
:
cp console.so io/console.so
cd -
mkdir -p tmp/x86_64-linux/stage/.libs/4.1.0/x86_64-linux/io
(cd tmp/x86_64-linux/io/console/4.1.0 && /bin/gmake install sitearchdir=../../../../../.libs/4.1.0/x86_64-linux/io sitelibdir=../../../../../.libs/4.1.0/x86_64-linux/io target_prefix=)
/bin/mkdir -p . ../../../../../.libs/4.1.0/x86_64-linux/io
exit > .sitearchdir.-.io.time
/bin/install -c -m 0755 console.so ../../../../../.libs/4.1.0/x86_64-linux/io
cp tmp/x86_64-linux/io/console/4.1.0/io/console.so tmp/x86_64-linux/stage/.libs/4.1.0/x86_64-linux/io/console.so

$ bundle exec rake test
(cd tmp/x86_64-linux/io/console/4.1.0 && /bin/gmake install sitearchdir=../../../../../.libs/4.1.0/x86_64-linux/io sitelibdir=../../../../../.libs/4.1.0/x86_64-linux/io target_prefix=)
/bin/install -c -m 0755 console.so ../../../../../.libs/4.1.0/x86_64-linux/io
cp tmp/x86_64-linux/io/console/4.1.0/io/console.so tmp/x86_64-linux/stage/.libs/4.1.0/x86_64-linux/io/console.so
Loaded suite /home/jaruga/.local/ruby-4.1.0-debug-3ef48ef9c8-openssl-4.1.0-7194354488/lib/ruby/gems/4.1.0+1/gems/rake-13.4.2/lib/rake/rake_test_loader
Started
Finished in 6.350711546 seconds.
---------------------------------------------------------------------------------------------------
34 tests, 135 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
---------------------------------------------------------------------------------------------------
5.35 tests/s, 21.26 assertions/s
```

**Comment by nobu** [comment]
Thank you for the confirmation.
